### ISSUE TITLE
Fix proc-macro2 compatibility issue with Rust 1.81.0

### ISSUE THREAD

**Issue by Pinellia577** [Pinellia577/raydium-cp-swap#2]
## Problem Description

The current version of the project fails to build with Rust 1.81.0 and newer versions due to a compatibility issue with proc-macro2. The specific error encountered is:

```
error[E0599]: no method named source_file found for struct proc_macro2::Span in the current scope
```

## Root Cause

This issue is caused by:
1. **Anchor version 0.31.0** - The current version has compatibility issues with newer Rust versions
2. **proc-macro2 version 1.0.94** - This version lacks support for newer Rust compiler features

## Environment Details

**Affected Rust versions:**
- Rust 1.81.0 and newer
- Rust 1.86.0 (confirmed affected)

**Current dependencies:**
- Anchor: 0.31.0
- proc-macro2: 1.0.94 (via Cargo.lock)

## Solution

Upgrade the following dependencies:

1. **Anchor Framework**: Upgrade from `0.31.0` to `0.31.1`
   - Update in `programs/cp-swap/Cargo.toml`
   - Update in `client/Cargo.toml`

2. **proc-macro2**: Will be automatically updated to `1.0.95` with Anchor 0.31.1

### 1. Update Program Dependencies

In `programs/cp-swap/Cargo.toml`:
```toml
[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", features = ["memo", "metadata"] }
```

### 2. Update Client Dependencies

In `client/Cargo.toml`:
```toml
[dependencies]
anchor-client = { version = "0.31.1" }
anchor-lang = { version = "0.31.1" }
```

### 3. Update Cargo.lock

Run the following commands to update the lock file:
```bash
cargo clean
cargo update
cargo build
```

## References

- **Original issue**: [Anchor GitHub Issue #3662](https://github.com/solana-foundation/anchor/issues/3662)
- **Upstream fix**: [raydium-io/raydium-cp-swap PR #45](https://github.com/raydium-io/raydium-cp-swap/issues/45)
- **proc-macro2 releases**: [dtolnay/proc-macro2 releases](https://github.com/dtolnay/proc-macro2/releases)

## Testing

After applying the fix, verify the build works with:
```bash
# Test program build
cargo build-sbf

# Test client build  
cd client && cargo build

# Run tests
anchor test
```

## Priority

**High** - This issue blocks development for users with Rust 1.81.0+ and is required for compatibility with current Rust stable releases.
